#! /usr/bin/env bash
# -----------------------------------------------------------------------------------
# This file will build Spatial4n and package the Nuget builds.
#
# Syntax:
#   build[.bat] [<options>]
#
# Available Options:
#
#   --configuration <Configuration>
#   -config <Configuration> - MSBuild configuration for the build.
#
#   --test
#   -t - Run the tests.
#
#   All options are case insensitive.
#
# -----------------------------------------------------------------------------------

if ! command -v pwsh &> /dev/null
then
    echo "Powershell Core could not be found. Please install version 3 or higher."
    exit
fi

pwsh -ExecutionPolicy bypass -Command "& './build.ps1'" "$@"